// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WelfareLink.CitizenManagement.API.Data;

#nullable disable

namespace WelfareLink.CitizenManagement.API.Migrations
{
    [DbContext(typeof(WelfareLinkDbContext))]
    partial class WelfareLinkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.Audit", b =>
                {
                    b.Property<int>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditID"));

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AuditedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FindingType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProgramID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuditID");

                    b.HasIndex("AuditedByUserId");

                    b.HasIndex("ProgramID");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.AuditLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.Benefit", b =>
                {
                    b.Property<int>("BenefitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BenefitID"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BenefitID");

                    b.HasIndex("ApplicationID");

                    b.ToTable("Benefits");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.Citizen", b =>
                {
                    b.Property<int>("CitizenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CitizenId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CitizenId");

                    b.HasIndex("UserId");

                    b.ToTable("Citizens");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.CitizenDocument", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentID"));

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileURI")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("DocumentID");

                    b.HasIndex("CitizenId");

                    b.ToTable("CitizenDocuments");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.ComplainceRecord", b =>
                {
                    b.Property<int>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordID"));

                    b.Property<int?>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<int?>("CitizenID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RaisedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ViolationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RecordID");

                    b.HasIndex("RaisedByUserId");

                    b.HasIndex("ResolvedByUserId");

                    b.ToTable("ComplianceRecords");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.Disbursement", b =>
                {
                    b.Property<int>("DisbursementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisbursementID"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("BenefitID")
                        .HasColumnType("int");

                    b.Property<int>("CitizenID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("OfficerID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DisbursementID");

                    b.HasIndex("BenefitID");

                    b.ToTable("Disbursements");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.EligibilityCheck", b =>
                {
                    b.Property<int>("CheckID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckID"));

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfficerID")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CheckID");

                    b.HasIndex("ApplicationID");

                    b.ToTable("EligibilityChecks");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.Resource", b =>
                {
                    b.Property<int>("ResourceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResourceID"));

                    b.Property<int>("ProgramID")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ResourceID");

                    b.HasIndex("ProgramID");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("CitizenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("CitizenId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.WelfareApplication", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationID"));

                    b.Property<int>("CitizenID")
                        .HasColumnType("int");

                    b.Property<int>("ProgramID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("SubmittedDate")
                        .HasColumnType("date");

                    b.HasKey("ApplicationID");

                    b.HasIndex("CitizenID");

                    b.HasIndex("ProgramID");

                    b.ToTable("WelfareApplications");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.WelfareApplicationDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<int>("DocumentID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationID");

                    b.HasIndex("DocumentID");

                    b.ToTable("WelfareApplicationDocuments");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.WelfareProgram", b =>
                {
                    b.Property<int>("ProgramID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramID"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EligibleGender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaxBenefitPerCitizen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RequiredDocuments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProgramID");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.Audit", b =>
                {
                    b.HasOne("WelfareLink.CitizenManagement.API.Models.User", "AuditedByUser")
                        .WithMany()
                        .HasForeignKey("AuditedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WelfareLink.CitizenManagement.API.Models.WelfareProgram", "WelfareProgram")
                        .WithMany()
                        .HasForeignKey("ProgramID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AuditedByUser");

                    b.Navigation("WelfareProgram");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.AuditLog", b =>
                {
                    b.HasOne("WelfareLink.CitizenManagement.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.Benefit", b =>
                {
                    b.HasOne("WelfareLink.CitizenManagement.API.Models.WelfareApplication", "WelfareApplication")
                        .WithMany("Benefits")
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WelfareApplication");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.Citizen", b =>
                {
                    b.HasOne("WelfareLink.CitizenManagement.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.CitizenDocument", b =>
                {
                    b.HasOne("WelfareLink.CitizenManagement.API.Models.Citizen", "Citizen")
                        .WithMany("CitizenDocuments")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.ComplainceRecord", b =>
                {
                    b.HasOne("WelfareLink.CitizenManagement.API.Models.User", "RaisedByUser")
                        .WithMany()
                        .HasForeignKey("RaisedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WelfareLink.CitizenManagement.API.Models.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RaisedByUser");

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.Disbursement", b =>
                {
                    b.HasOne("WelfareLink.CitizenManagement.API.Models.Benefit", "Benefit")
                        .WithMany("Disbursements")
                        .HasForeignKey("BenefitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benefit");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.EligibilityCheck", b =>
                {
                    b.HasOne("WelfareLink.CitizenManagement.API.Models.WelfareApplication", "WelfareApplication")
                        .WithMany("EligibilityChecks")
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WelfareApplication");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.Resource", b =>
                {
                    b.HasOne("WelfareLink.CitizenManagement.API.Models.WelfareProgram", "Program")
                        .WithMany("Resources")
                        .HasForeignKey("ProgramID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.User", b =>
                {
                    b.HasOne("WelfareLink.CitizenManagement.API.Models.Citizen", "Citizen")
                        .WithMany()
                        .HasForeignKey("CitizenId");

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.WelfareApplication", b =>
                {
                    b.HasOne("WelfareLink.CitizenManagement.API.Models.Citizen", "Citizen")
                        .WithMany()
                        .HasForeignKey("CitizenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WelfareLink.CitizenManagement.API.Models.WelfareProgram", "Program")
                        .WithMany("WelfareApplications")
                        .HasForeignKey("ProgramID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizen");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.WelfareApplicationDocument", b =>
                {
                    b.HasOne("WelfareLink.CitizenManagement.API.Models.WelfareApplication", "WelfareApplication")
                        .WithMany("ApplicationDocuments")
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WelfareLink.CitizenManagement.API.Models.CitizenDocument", "CitizenDocument")
                        .WithMany()
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CitizenDocument");

                    b.Navigation("WelfareApplication");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.Benefit", b =>
                {
                    b.Navigation("Disbursements");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.Citizen", b =>
                {
                    b.Navigation("CitizenDocuments");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.WelfareApplication", b =>
                {
                    b.Navigation("ApplicationDocuments");

                    b.Navigation("Benefits");

                    b.Navigation("EligibilityChecks");
                });

            modelBuilder.Entity("WelfareLink.CitizenManagement.API.Models.WelfareProgram", b =>
                {
                    b.Navigation("Resources");

                    b.Navigation("WelfareApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
