// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WelfareLink.Data;

#nullable disable

namespace WelfareLink.Migrations
{
    [DbContext(typeof(WelfareLinkDbContext))]
    [Migration("20260327122705_foriegnKeyMap")]
    partial class foriegnKeyMap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WelfareLink.Models.Benefit", b =>
                {
                    b.Property<int>("BenefitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BenefitID"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BenefitID");

                    b.ToTable("Benefits");
                });

            modelBuilder.Entity("WelfareLink.Models.Disbursement", b =>
                {
                    b.Property<int>("DisbursementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisbursementID"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("BenefitID")
                        .HasColumnType("int");

                    b.Property<int>("CitizenID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("OfficerID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DisbursementID");

                    b.HasIndex("BenefitID");

                    b.ToTable("Disbursements");
                });

            modelBuilder.Entity("WelfareLink.Models.EligibilityCheck", b =>
                {
                    b.Property<int>("CheckID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckID"));

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfficerID")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CheckID");

                    b.HasIndex("ApplicationID");

                    b.ToTable("EligibilityChecks");
                });

            modelBuilder.Entity("WelfareLink.Models.Resource", b =>
                {
                    b.Property<int>("ResourceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResourceID"));

                    b.Property<int>("ProgramID")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ResourceID");

                    b.HasIndex("ProgramID");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("WelfareLink.Models.WelfareApplication", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationID"));

                    b.Property<int?>("BenefitID")
                        .HasColumnType("int");

                    b.Property<int>("CitizenID")
                        .HasColumnType("int");

                    b.Property<int>("ProgramID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("SubmittedDate")
                        .HasColumnType("date");

                    b.Property<int?>("WelfareProgramsProgramID")
                        .HasColumnType("int");

                    b.HasKey("ApplicationID");

                    b.HasIndex("BenefitID");

                    b.HasIndex("WelfareProgramsProgramID");

                    b.ToTable("WelfareApplications");
                });

            modelBuilder.Entity("WelfareLink.Models.WelfareProgram", b =>
                {
                    b.Property<int>("ProgramID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramID"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProgramID");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("WelfareLink.Models.Disbursement", b =>
                {
                    b.HasOne("WelfareLink.Models.Benefit", "Benefit")
                        .WithMany("Disbursements")
                        .HasForeignKey("BenefitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benefit");
                });

            modelBuilder.Entity("WelfareLink.Models.EligibilityCheck", b =>
                {
                    b.HasOne("WelfareLink.Models.WelfareApplication", "WelfareApplication")
                        .WithMany("EligibilityChecks")
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WelfareApplication");
                });

            modelBuilder.Entity("WelfareLink.Models.Resource", b =>
                {
                    b.HasOne("WelfareLink.Models.WelfareProgram", "Program")
                        .WithMany("Resources")
                        .HasForeignKey("ProgramID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("WelfareLink.Models.WelfareApplication", b =>
                {
                    b.HasOne("WelfareLink.Models.Benefit", null)
                        .WithMany("WelfareApplications")
                        .HasForeignKey("BenefitID");

                    b.HasOne("WelfareLink.Models.WelfareProgram", "WelfarePrograms")
                        .WithMany("WelfareApplications")
                        .HasForeignKey("WelfareProgramsProgramID");

                    b.Navigation("WelfarePrograms");
                });

            modelBuilder.Entity("WelfareLink.Models.Benefit", b =>
                {
                    b.Navigation("Disbursements");

                    b.Navigation("WelfareApplications");
                });

            modelBuilder.Entity("WelfareLink.Models.WelfareApplication", b =>
                {
                    b.Navigation("EligibilityChecks");
                });

            modelBuilder.Entity("WelfareLink.Models.WelfareProgram", b =>
                {
                    b.Navigation("Resources");

                    b.Navigation("WelfareApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
